version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - aws ecs describe-task-definition --task-definition LaravelWebAppTask
  post_build:
    commands:
      - echo Nothing to do in the post_build phase...
