version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - CD_DIR='./cd/deploy'
      - echo ${STAGE_ID}
      - VERSION_TAG=$(${CD_DIR}/lookup_git_version_tag_from_stage_tag.sh ${STAGE_ID})
      - echo ${VERSION_TAG}
  build:
    commands:
      - aws ecs describe-task-definition --task-definition LaravelWebAppTask
  post_build:
    commands:
      - echo Nothing to do in the post_build phase...
