version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
      - ps -p $$
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - ps -p $$
  build:
    commands:
      - pwd
      - ls -l
      - aws --version
      - env
      - echo Nothing to do in the build phase...
      - ps -p $$
  post_build:
    commands:
      - echo Nothing to do in the post_build phase...
      - ps -p $$
