version: "3"
services:
  mysql:
    image: "mysql:8-debian"
    container_name: "mysql-laravel"
    environment:
      MYSQL_ROOT_PASSWORD: local-password
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    restart: "unless-stopped"
  locals3:
    image: "minio/minio"
    container_name: "local-s3-minio"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: "minio_access_key"
      MINIO_SECRET_KEY: "minio_secret_key"
      MINIO_ROOT_USER: "mineo"
      MINIO_ROOT_PASSWORD: "mineo_password"
    command: [ 'server', '/data', '--console-address', ':9001' ]
    volumes:
      - ./data/s3/data:/data
