version: "3"
services:
  mysql:
    image: "mysql:8-debian"
    container_name: "mysql-laravel"
    environment:
      MYSQL_ROOT_PASSWORD: local-password
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    restart: "unless-stopped"
  locals3:
    image: "bitnami/minio"
    container_name: "local-s3-minio"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "mineo"  # concurrently access key
      MINIO_ROOT_PASSWORD: "mineo_password" #  concurrently secret key
      MINIO_DEFAULT_BUCKETS: "laravel-test-upload-bucket:public"
