version: 0.2
env:
  shell: bash
  variables:
    RESULT: false
    IMAGE_TAG: '1.2.3'
    SLACK_WEBHOOK_URL: ''
phases:
  build:
    commands:
      - echo 'this is a pen !'
      - echo 'hoge' | grep 'fuga'
      - RESULT=true
    finally:
      - ./notification_build.sh ${RESULT}
