version: 0.2
env:
  shell: bash
  parameter-store:
    SLACK_WEBHOOK_URL: "alws-slack-webhook-url"
  variables:
    RESULT: false
    IMAGE_TAG: '1.2.3'
    SCRIPT_PATH : './doc/aws/samples/codebuild-local-exec'
phases:
  build:
    commands:
      - env | sort
      - echo 'hoge' | grep 'huga'
      - RESULT=true
    finally:
      - ${SCRIPT_PATH}/notification_build.sh ${RESULT}
